### PR TITLE
Edited information about NSPro

### PR DESCRIPTION
**Pull request by AndyLow91**
Nothing major, just some updated information with links and pricing.

### CODE REVIEW

**Comment by logangreenwood** [comment]
Are you able to help?



Sent from Yahoo Mail for iPhone


On Thursday, August 8, 2024, 1:47 PM, Andy Low ***@***.***> wrote:


Nothing major, just some updated information with links and pricing.

You can view, comment on, or merge this pull request online at:

  https://github.com/nightscout/nightscout.github.io/pull/214

Commit Summary
   
   - 9a2908a Edited information about NSPro

File Changes 
 
(1 file)
   
   -  M docs/index.md (26) 

Patch Links:
   
   - https://github.com/nightscout/nightscout.github.io/pull/214.patch
   - https://github.com/nightscout/nightscout.github.io/pull/214.diff

**Comment by AndyLow91** [comment]
@logangreenwood  I'm not sure what you're looking for help with, exactly? I can sure try.

**Comment by logangreenwood** [comment]
I use night scout to track my sons type one diabetes, I really don’t have a clue how i even got night scout working, but some how i did and i pay someone $7 a month and really don’t know what im paying for. I thought it was to take care of my night scout site? Is your company the one that i pay? If she can you explain what I’m paying? Like what service do you do? I’m asking because my night scout is no longer working and need to know if you all can help getting going, and if that is what I’m paying the $7 a month for or if I’m paying for something totally different? This is what i see when i open my app



Sent from Yahoo Mail for iPhone


On Thursday, August 8, 2024, 3:00 PM, Andy Low ***@***.***> wrote:




@logangreenwood I'm not sure what you're looking for help with, exactly? I can sure try.

**Comment by psonnera** [comment]
@logangreenwood 7$/Month sounds like Heroku, not https://nightscoutpro.com
This GitHub repo is regarding documentation, not support, but if you're using Heroku I would start there https://nightscout.github.io/troubleshoot/troubleshoot/
For better help, join us on Facebook https://www.facebook.com/groups/cgminthecloud or in Discord https://discord.gg/zg7CvCQ

**Pull request merged**
