### PR TITLE
Information added regarding Nightscout.Pro

### PR DESCRIPTION
**Pull request by AndyLow91**
I'm requesting the addition of various information about Nightscout.Pro. I have added as much information as possible in the interest of transparency but I'm also happy to answer any questions in addition to this.

### CODE REVIEW

**Comment by sulkaharo** [comment]
So, +1 for adding the new provider in, but I think it'd be good if these docs had absolutely minimal amount of information about how the setup of the commercial offerings and just linked to external docs (so in addition to having most of the information in this PR be hosted somewhere else, the T1Pal section would be cut down significantly from what it is now). The rationale for this is simply that maintaining these docs is quite a lot of effort and for anyone offering Nigthscout as a service, documentation maintenance should be as close to 100% the burden of the service provider as possible, so the costs of offering the service are not offloaded to the community. Plus making edits to these docs can be slower than needed by a service provider as we can't give any guarantee of how frequently we'll merge changes.

**Comment by AndyLow91** [comment]
@sulkaharo I agree with what you say about the burden lying with the provider. Happy to cut down on the information as required (I just went for a similar approach as T1Pal and NS10BE).

Can we all have an open conversation about what information is suitable for the official docs somewhere?

Also, would you mind helping me understand the impact this is having on the community so I can help minimise it? My thoughts were that Each service provider would be the owner of their own information page within the docs, so it shouldn't have much impact on community resources, but perhaps I am wrong?

As a slight side-note, I am also keen to help out with the community aspect of Nightscout, so I could help ease some of the burden somewhere. Not sure where best to start with this.

**Comment by bewest** [comment]
Howdy Andy.  I do want the people listed to feel pressure to use the money collected to benefit Nightscout and to be sustainable and participate in sustainability.  Part of sustainability is having a plan for managing capacity and volume.  If we take the 20k Nightscouters that Salesforce counted as a lower bound, we need documentation to that can scale to meet the audience.

While it might make sense to organize an network for small, organized, manual neighborhood hosters like Nightscout.pro, since the capacity is limited, it should be reserved for people who need help and cannot afford one of the other options.  I'm open to suggestions for how to ensure the limited capacity offered by Nightscout neighbors is reserved for people who need the help while the community at large supports Nightscout through sustainable means.  If new hosting with limited availability for less than 200 seats is available, how do we effectively communicate this?

**Comment by sulkaharo** [comment]
Basically, my expectation is that if someone charges money for Nightscout, they will operate the service as a business and we need to have as clear distinction between the business and the open source effort as possible. These docs are about the open source side and as such should point people to business operators who are offering Nightscout (as I believe it's absolutely great people have the option to skip the installation process they're likely struggling with), but any service level docs and associated technical support website should be separate from the open source project.

I'm slightly confused by Ben's remark about 200 users - can you please confirm you intend to scale the service to meet demand? I'm not sure we should list services here that don't intend to aim provide Nightscout to everyone who navigates to the service provider through these docs.

**Comment by AndyLow91** [comment]
@bewest I'm not sure why you think I only have the capacity for 200 or less?

Let me assure both yourself and @sulkaharo that I can and will host Nightscout for any user that needs/wants it. Without any reconfiguration at all, I've calculated I currently have the capacity for ~700 Nightscout instances hosted on a dedicated server in a trusted and secure data centre with regular off-site backups. If demand turns out to be greater than this, then I have no issue scaling the operation to meet it. I am quite experienced in system admin and do this and back-end development for a very large international corporation.

@sulkaharo I am completely in agreement and happy to keep these docs more about the open-source project rather than any paid service. It would be nice to have a mention in there so the public knows there is an option. Where would be the preferred location?

**Comment by AndyLow91** [comment]
@sulkaharo @bewest @psonnera - I have removed most of the information now from the Nightscout.Pro page to simply include some pricing detail and point the user to the Nightscout.Pro website.

Is there any other information you guys would like or for me to update?

**Pull request merged**
