### PR TITLE
wip

### PR DESCRIPTION
**Pull request by sbmsr**

### CODE REVIEW

**Review by psonnera — COMMENTED** [review]
Oh, I see. That's a full deployment including a new database. Now I understand why you want to add a credit card for this. Do you have an idea of the monthly cost for a looper (i.e.high profile Nightscout)?

**Comment by psonnera** [comment]
"Now lets deploy nightscout. We can trigger a deployment by modifying our fork, or via the [railway cli](https://docs.railway.app/develop/cli) by running [railway up](https://docs.railway.app/develop/cli#deploy)" this is out of reach for most people. Any idea to make it easier? Maybe give an example of a fork modification?

**Comment by sbmsr** [comment]
@psonnera Yes! I was intending on adding that in before merge. I should have put a do-not-merge label

**Comment by psonnera** [comment]
@sbmsr no problem, the page is still WIP you can carry on (don't really want to revert as I just threw 3 hours of stash with a wrong click). Are you sure you need a credit card for verification? I always managed to get the 500 hours without it... I will work on the migration part keeping the MongoDB Atlas database. I'm afraid running both site and database on 500 hours won't last more than a week...

**Pull request merged**
