### PR TITLE
Navid 2024 06 07

### PR DESCRIPTION
**Pull request by Navid200**
The purpose of this PR is to add a Google Cloud page.

It is possible that I may have mistakes.
I cannot see what this will look like after it is built.

So, please fell free to reject.
Please let me know how I can improve it.

Thanks

### CODE REVIEW

**Comment by Navid200** [comment]
This is what I was hoping it would look like.
Screenshot 2024-06-07 175523

**Comment by Navid200** [comment]
Awesome!
Thanks

**Comment by psonnera** [comment]
Looks good. Logo name typo https://github.com/nightscout/nightscout.github.io/commit/098992c801d2bb4583a891f0a991d7ed9e49f082. Thanks a lot @Navid200.

**Comment by Navid200** [comment]
Sorry about that

Thanks for the fix

**Pull request merged**
