### PR TITLE
equalize parity of information for common entry point

### PR DESCRIPTION
**Pull request by bewest**
Make sure that when people post only this link they get basic parity in exposure to options.

### CODE REVIEW

**Review by psonnera — CHANGES_REQUESTED** [review]
Ok to delete "History". Note DIY comments are OT since those looking at this page are using a DIY site, so they know. Same for "Use a service": wrong public. Those reading this want to migrate an existing site. Note that T1Pal doesn't offer data migration unlike all proposed options in this page.
Same comment for the hosted solutions below. Wrong contents: people are migrating, not creating a new Nightscout site.

**Review by psonnera — COMMENTED** [review]
Free accounts are not a problem for Nightscout. The dbsize plugin offers all necessary information, as well as administrative tools. They've been indeed added for Atlas. The problem is how users maintain their Nightscout site. Loopers and AAPS'ers should secure storage going for an M2 if they want: why should they avoid MongoDB??? Any technical reason?
Note: Obviously paying 9$/month for an M2 on a self maintained DIY Nightscout site might not be a very smart choice seen hosted solutions.

**Review by psonnera — COMMENTED** [review]
Same than above, why not buy storage from Atlas? Any technical reason?

**Comment by bewest** [comment]
Thanks for comments, I will try to integrate them.
The advice I removed includes recommends deleting data.  For people that are deleting data, migrating their current data set is indistinguishable from starting over in the next 90 days.
My concern with recommending purchasing MongoDB Atlas storage is that I don't consider it to be a good buy for the money for personal use like Nightscout.  It's intended for enterprise and multinational corporations.  Both Sulka and Jason and I have repeatedly recommended Digital Ocean for compute and storage.
The feedback from xdrip team on Google with 20GB storage has been good as well, I think we would consider recommending that.  Digital Ocean remains the best buy for DIY loopers of all stripes who absolutely need to control their own database and Nightscout versions, and there seem to be fewer geo restrictions as well.  The xdrip solution is very creative, a similar approach might be ideal for Digital Ocean to enable more DIY use.

**Comment by bewest** [comment]
Do you have any specific improvements or changes?  Any place where we are going to advertise strongly for third party hosts needs to also include access to equivalent information for the folks directly supporting Nightscout. It seems that the docs keep shifting to potentially avoid mentioning sustainable Nightscout efforts on FB?  We've already agreed on this wording, although I'm open to other suggestions.  @sulkaharo?  I can add more specificity to say we recommend Digital Ocean for storage for DIY, but I don't think this will resolve your concerns, @psonnera.

**Comment by psonnera** [comment]
@bewest every single new_user and migration page include the disclaimer "Consider [Nightscout as a service](https://nightscout.github.io/#nightscout-as-a-service) as an option." in font-size:larger. This documentation is not strong advertisement but just a list of available DIY solutions. I can add more disclaimers to make sure people know what to expect but I would prefer not having T1Pal written all over the place. Let me do some changes in your direction and you'll tell me if it's what you want.
image

**Comment by psonnera** [comment]
i.e. not like that

**Comment by bewest** [comment]
Thanks for your consideration. I'm not arguing for dedicated providers to be more prominent than others and willing to consider rewording, etc.  The goal is that for entry points summarizing things for people, that all the options that are a good fit are given equitable footing.  On this page in particular, that seems to mean a heading and blurb about everyone so people can inform their migration from Heroku.  I'm open to adjusting to feedback.

**Pull request closed without merging**
