### PR TITLE
add ns.10be.de as managed service

### PR DESCRIPTION
**Pull request by zehnBE**

### CODE REVIEW

**Comment by zehnBE** [comment]
add ns.10be.de as managed service

**Comment by psonnera** [comment]
Sure! Wanted to ask you before!

**Comment by marionbarker** [comment]
The deployed pages were not updated.  I added an [Automatic Publish pull request](https://github.com/nightscout/nightscout.github.io/pull/125)

This works for loopdocs - I hope it works for this repository.

**Comment by psonnera** [comment]
@bewest @sulkaharo @zehnBE please review https://github.com/nightscout/nightscout.github.io/commit/4b78f4610108ab17609fbb13f5ff8ccd50d7ac60 before publishing pages to confirm it matches your views.

**Comment by bewest** [comment]
Looks good to me; there might be a few grammar tweaks.  Welcome @zehnBE.  I do believe Nightscout docs should be inclusive. :smiley_cat:

**Pull request merged**
