### PR TITLE
Minor typo fixes and adjusted links

### PR DESCRIPTION
**Pull request by opinel**
After following the installation guide, I spotted a few typos that I fixed.
Moreover, I addressed mkdocs warnings on broken links, especially in local-dev mode.

### CODE REVIEW

**Review by paulplant — COMMENTED** [review]
The changes to uploaders.md will cause a merge conflict and should be dropped in order to merge in #104 

All other changes look good!

**Comment by opinel** [comment]
I resolved the merge conflict.

**Comment by psonnera** [comment]
@opinel don't hate me for that please, but I had an urgent request to document security implementation and I completely forgot to merge your changes before deploying. Can you check the other two remaining conflicts? Since modifications should slow down, further PRs will be smoother. Don't stop, thanks for your help!

**Comment by opinel** [comment]
@psonnera no worries. I resolved the conflicts.

**Pull request merged**
