### PR TITLE
Added Uptime robot to Brand new NS

### PR DESCRIPTION
**Pull request by bjornoleh**
This is just a simple test for me of the concept of contributing to the documentation, and my first PR to any Open source project. If it can be accepted as-is, even better. I hope this PR won't violate any copyright or licence issues. The source is from within the Nightscout project, so I assume it's all good. Please let me know if there are any guidelines I have missed in this respect.

Is is appropriate to keep a reference to the source in the file (as done in this PR), or is it enough to do this in comments? 

Source: http://www.nightscout.info/wiki/welcome/set-up-nightscout-using-heroku), with only minor formatting changes.

### CODE REVIEW

**Review by scottleibrand — APPROVED** [review]

**Comment by sulkaharo** [comment]
Sorry for the delay - I have no idea why this has been recommended for new setups. The uptime robot is not needed if the user is actually uploading data into Nightscout, as the REST API calls already keep the site alive. The only user would need this is someone who injects data directly into MongoDB, but that use case is not supported anymore.

**Comment by bjornoleh** [comment]
Hi, I recon that in many cases during normal use, and with other
applications pushing data into NS, then the uptime robot is superfluous.

We have it set up for two sites in normal use, and that works fine. But we
have another NS instance only used for testing, and without uptime robot.
Whenever I check in on this site, it is asleep. There is even a zzzzzzz symbol
for this app in Heroku. It takes some effort to wake it up again, which
would have been unacceptable in normal use.

The testing site is only fed BG data through Dexcom share / Bridge, and not
linked to any APS like Loop. Perhaps that is the reason for it falling
asleep?
Screenshot_20200925-144750_Chrome


fre. 25. sep. 2020, 14:25 skrev Sulka Haro <notifications@github.com>:

**Comment by sulkaharo** [comment]
Ah right - yes if someone uses the Dexcom bridge and does not have a client loading the data (such as a smartwatch, phone app, Loop or OpenAPS), the site will go to sleep. Ping @psonnera who's big update caused this to confict

**Comment by psonnera** [comment]
You both lost me on this one. @bjornoleh you have bridge in Heroku ENABLE and your site falls asleep? Or is it just the wiki that forgot to mention it is mandatory?

**Comment by bjornoleh** [comment]
Hi @psonnera , the testing site is with Bridge only, and is not being fed with data from Loop etc. This NS site goes to sleep quite quickly, so in this use case, an uptime robot would help. 

The pull request is just me adding the text that was in the old documentation. In part just as a learning experience to see if I could do it, as I am not a developer.

http://www.nightscout.info/wiki/welcome/set-up-nightscout-using-heroku

I believe it is useful with an uptime robot in some cases, so I added this bit which was missing from the new info docs.

I guess you were mentioned now since my PR had been waiting for a while, and now that you have also made changes to this file there are some conflicts that must be resolved. I don't know how that is done, but happy to learn  :-)

Edit: and I do have bridge in ENABLE, no problems there.

**Comment by psonnera** [comment]
Oh, got you: the green and purple instructions. Good. That's mine. For the uptime robot, as @sulkaharo wrote, it shouldn't happen in production since the uploader sending BG should keep it awake.

**Comment by bjornoleh** [comment]
Yes, probably. Would someone use NS with Dex Bridge only, or some similar setup? 

Would there be some benefits of uptime robot for other cases, like after communication problems with the uploader phone, or would NS wake up instantaneously when fed new data?

Any downsides to using uptime robot? It's very easy to set up at least.

Its up to you @sulkaharo et al to decide if this is to be a part of the docs or not.

**Comment by sulkaharo** [comment]
So to comment - yea it sounds like this should be described in the documentation, but being clear that this is only needed specifically if using Dex Share and _not_ using any uploaders/apps to load the data, so people don't see this as yet another service to setup

**Comment by bjornoleh** [comment]
Thanks @sulkaharo, that sounds reasonable. It seems like the structure of the documents has changed quite a bit lately (looking good!  :-) ), so maybe this PR is not so easily merged now. 

Perhaps @psonnera has an idea about where to put it? Just grab it as you see fit, or maybe I will just make a new PR for it later?

**Comment by psonnera** [comment]
@bjornoleh I'd like to put it in the troubleshooting section (not yet ready) for bridge users seeing their NS falling asleep. With a link in new_user.md. That ok?

**Comment by bjornoleh** [comment]
Sure, sounds good. You can do it as you like, or ping me here when it is
time.

ons. 30. sep. 2020, 21:33 skrev Patrick Sonnerat <notifications@github.com>:

**Comment by bjornoleh** [comment]
Hi @psonnera,  I have seen a couple of users actually needing uptime robot recently. Here is a different use case, with carelink (I'm not sure what that is).

https://www.facebook.com/groups/cgminthecloud/permalink/3437948612993037/

**Comment by psonnera** [comment]
You are definitely right. Will do ASAP.

**Comment by bjornoleh** [comment]
Closed by https://github.com/nightscout/nightscout.github.io/commit/b427d3c9b8b33ae6dd7ac43326ab85ca530c5de0

**Pull request closed without merging**
