### PR TITLE
restructure Nightscout is free discussion

### PR DESCRIPTION
**Pull request by bewest**
Again try to clarify and deescalate language used.  This change makes explicit
what is free and the ways in which it may not represent the free experience
implied otherwise.

Nightscout developers cannot control the price of third party servers.  We
can't make this claim and have never supported it.  We are now being held responsible for making it true even though it's not feasible.

### CODE REVIEW

**Comment by bewest** [comment]
This lays out examples for how to discuss "what is free" without accusing participants of harming the ecosystem, and without confusing people expecting a year of free mission-critical application support for Loop.  This offers a useful starting place to add fly.io and railway, as discusssed in https://github.com/nightscout/nightscout.github.io/issues/147

**Review by psonnera — COMMENTED** [review]
I liked @sulkaharo comments and James's post as background data regarding this, and this is why I added them, but if you don't, no problem. Let's remove the background discussion from this documentation.

**Review by psonnera — CHANGES_REQUESTED** [review]
I do not believe fly.io or Railway have been accepted as the new DIY solution instead of Heroku. I would not mention them at this point, Should they be integrated as a classic DIY solution warnings should be added regarding the limitations of the free tier.

**Comment by bewest** [comment]
Ok, they are removed from the front page with a bit more nuanced discussion, and updated with the latest information I could find.  Also, all the vendors with some form of a stub page are linked.  I think this will help people see where they can make a difference and participate.

**Pull request merged**
