### PR TITLE
Add automatic publish of Nightscout pages

### PR DESCRIPTION
**Pull request by marionbarker**
Add an action to automatically update the deployed pages on a push to branch source.
Options to edit file to require manual Action are included if that is the preferred approach.

### CODE REVIEW

**Comment by psonnera** [comment]
Very nice feature thank you! I was still working on #124 and usually deploy manually gh-pages. Let me think about it. I mean the integration of another NS as a service has cascading impact on the menus, etc...

**Comment by marionbarker** [comment]
I modified the publish.yml to make the publish step manual.
I learned this technique from @cfaagaard

**Comment by bewest** [comment]
Continuous integration, continuous delivery, for the win.  Do you prefer the manual publish step?  For projects like these, it's often desirable to have the publishing automatically follow the main branch. Regularly sending all changes through 2 rounds pull requests to get from a editor's topical change, to the group staging area, to the main docs area usually provides plenty of adequate review; I'd be comfortable publishing automatically in that scenario.  It's possible a site like readthedocs.com can render several versions of the docs with a switcher to navigate versions (AndroidAPS and openaps are set up this way).

**Comment by psonnera** [comment]
I really like the AAPS documentation but somehow fear the transition to Sphinx. Still, I agree that this platform would be much better also for multiple languages. Now, MkDocs is really easy to use and nevertheless already stops many potential contributors.
There's no problem to automatically publish, that will force me to better use some GitHub mechanisms. 
Still, this would make more sense with multiple collaborators and an active project, where in our case there are very few... but extremely appreciated contributors. Having Issues and PRs is always a pleasure. More than reading that the doc sucks, on (luckily few) FB posts.

**Comment by psonnera** [comment]
@marionbarker wow that is an extremely neat feature. I had a couple of months fighting with authentication in GitBash and needed to publish through GitHub desktop app. I really like that. Thanks a lot!

**Pull request merged**
