### PR TITLE
Revert "inclusive nightscout community values"

### PR DESCRIPTION
**Pull request by sulkaharo**
I suggest we revert this for now. This documentation site is for the open source project and _really_ needs to stay vendor neutral, where whatever mentions providers get here, the format has to be such that we'd be comfortable with any vendor (including one of the Big Pharma) opening a Nightscout service tomorrow and getting exactly as many mentions here as other providers.

### CODE REVIEW

**Comment by psonnera** [comment]
I am discussing with @bewest the best approach to satisfy all parties and widen the DIY section. Unsure on best approach yet.

**Comment by marionbarker** [comment]
I like the phrase "Nightscout as a Service" as opposed to "Paid Solutions" - because DIY folks can pay for the hosting if they choose. 

I think other "Nightscout as a Service" providers **that want to be listed** should be added to index.md.  If there were other options, I'd want to know what they are.  I will not comment on the other edits that I'm sure you will handle.  

I built my first Nightscout site in 2015 (Azure); later Heroku after I'd been on Loop for a while. I have used t1pal since their beta-test days.  There have been a few bumps, but I'm happy to pay someone to handle that part of my life. And let me take the opportunity to thank you all for your contributions to the DIY community which has made such a difference in my life.

**Comment by jlmgithub** [comment]
I'd suggest Nightscout as a Fee-based Service or even monthly fee-based service.

**Comment by sulkaharo** [comment]
Software as a service is pretty established as a term and Nightscout as a service sounds great. I don't see any need to add the fee word in there - some might be for free, some might charge for the service.

Might be worth also adding the TINSTAAFL clause to the "free" DIY hosting setup: you might not pay for service, but also this means you'll be spending a lot of hours on this.

**Comment by psonnera** [comment]
Let me grab all non disruptive changes and apply comments above to maintain consistency. I'll then work on DIY solutions outside of Heroku. Suggested DIY were Ocean Drop, Azure, containers, Synology, personal servers, ... Add yours... Obviously T1Pal will be present but I'm not for other paid hosted services unless approved by developers.

**Comment by bewest** [comment]
Reading through the changes, it appears the comments may have already been covered?  If possible, I'd like to close this pull request in favor of creating a new one, or more, to add more options and details about what to expect from each option and modulate tone if needed.  T1Pal is mentioned on only two new pages (not every page), once as requested under Nightscout as a service, and once in a place where it's relevant for a specific error, and once as an experiment on the update stack page.  If there are issues with wording in one of these three places, lets fix those.

The bigger decision is going forward as @psonnera hints at, should we split pages up by A.) vendor or by B.) stage in the experience?
Organizing pages by vendor first means creating a set of pages for Heroku/Salesforce plus another section of pages for T1Pal, plus another for Digital Ocean, etc.  This will keep the details separated from each other, which may make things easier to edit.  However, this would also keep the people using Heroku and updating their "stacks" continuing to do so, even if that's not what they value.  Organizing pages by journey or experience means:  one section for getting started (Day 1),  different section for maintenance and updates (Day 2), yet another section for ongoing usage.  Inside these sections, each of the vendors could be listed so that the audience can compare and contrast the tasks.  

I don't have an opinion on which of the above is better (A or B) and view this as a tough editing decision.  If there's any interest, I'd be willing to sponsor a workshop to help gather more input and feedback.  The "update stack" page is slightly different from the others.  Most do mention "Nightscout as a service" with a link back to the list of services.  However the "Update stack" page does mention T1Pal instead of "see list of Nightscout as as service" link.  Should this be changed to match the others?  In some ways changing it means the update stack page to match the others would seem to a be a preference for choice A: organize by vendor.  On the other hand, choosing to keep "Update stack" page as-is might be a preference for choice B: organize by journey and experience.  I'm sure there are other perspectives, but this was mine in trying to add Heroku and T1Pal, especially in response to multiple Heroku issues.  Loopdocs eliminated all mention of Nightscout setup which increased my perception of the need to add more discussion to the options available besides Heroku.  Looking forward to working on adding additional vendors as well to help make sure more people depending on different plugins can get what they need.

**Comment by psonnera** [comment]
Agreed. Let's move forward from the current state. This is a major modification to the pages layout that will require time. First step will be to split DIY solutions by vendor. Closing for now.

**Pull request closed without merging**
